CREATE TABLE IF NOT EXISTS request
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created   TIMESTAMP WITHOUT TIME ZONE,
    event     BIGINT,
    requester BIGINT,
    status    varchar(25)                                    NOT NULL
);
