CREATE TABLE IF NOT EXISTS request
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created   TIMESTAMP WITHOUT TIME ZONE,
    event     BIGINT REFERENCES event (id) ON DELETE CASCADE NOT NULL,
    requester BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    status    varchar(25)                                    NOT NULL
);
