CREATE TABLE IF NOT EXISTS event
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          VARCHAR(2000),
    category_id         BIGINT,
    confirmed_requests  BIGINT,
    description         VARCHAR(7000),
    event_date          TIMESTAMP WITHOUT TIME ZONE,
    created_on          TIMESTAMP WITHOUT TIME ZONE,
    initiator_id        BIGINT REFERENCES users(id) ON DELETE CASCADE,
    location_id         BIGINT REFERENCES location(id) ON DELETE CASCADE,
    paid                BOOLEAN,
    participant_limit   BIGINT,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    request_moderation  BOOLEAN,
    state               VARCHAR(50),
    title               VARCHAR(120),
    -- расчетное поле из сервиса статистики, в бд не пересчитывается
    views               BIGINT
);