CREATE TABLE IF NOT EXISTS event
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          VARCHAR(2000),
    category_id         BIGINT,
    confirmed_requests  BIGINT,
    description         VARCHAR(7000),
    event_date          TIMESTAMP WITHOUT TIME ZONE,
    created_on          TIMESTAMP WITHOUT TIME ZONE,
    initiator_id        BIGINT,
    location_id         BIGINT,
    paid                BOOLEAN,
    participant_limit   BIGINT,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    request_moderation  BOOLEAN,
    state               VARCHAR(50),
    title               VARCHAR(120),
    -- расчетное поле из сервиса статистики, в бд не пересчитывается
    views               BIGINT
);

CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN,
    title  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS location
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC(9, 6) NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lon NUMERIC(9, 6) NOT NULL CHECK (lon BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_location_lat on location (lat);
CREATE INDEX IF NOT EXISTS idx_location_lon on location (lon);
CREATE INDEX IF NOT EXISTS idx_location_coords on location (lat, lon);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id BIGINT REFERENCES compilation (id) ON DELETE CASCADE NOT NULL,
    event_id       BIGINT REFERENCES event (id) ON DELETE CASCADE       NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comment
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(4000)                                  NOT NULL,
    status    VARCHAR(50)                                    NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE                    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_id  BIGINT REFERENCES event (id) ON DELETE CASCADE NOT NULL,
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_comment_event_id_created ON comment (event_id, created DESC);
CREATE INDEX IF NOT EXISTS idx_comment_author_id_created ON comment (author_id, created DESC);
CREATE INDEX IF NOT EXISTS idx_comment_status_created ON comment (status, created DESC);

CREATE TABLE IF NOT EXISTS subscriptions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    subscription_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    UNIQUE (user_id, subscription_id)
)